import Head from "next/head";
import React, { useEffect } from "react";
// import Header from "../components/header/Header";
import CardSlide from "../components/header/CardSlide";
// import Navbar from "../components/home/Navbar";
import Header from "../components/home/Header";
import NewCollections from "../components/home/NewCollections";
import BestSeller from "../components/home/BestSeller";
import OurProducts from "../components/home/OurProducts";
import Reviews from "../components/home/Reviews";
import Policies from "../components/home/Policies";
import Footer from "../components/home/Footer";
import Newsletter from "../components/home/Newsletter";

export default function Home({ getUser }) {
  useEffect(() => {
    return () => {
      let subscribe = true;
      if (subscribe) {
        getUser();
      }

      return () => {
        subscribe = true;
      };
    };
  }, []);

  return (
    <>
      <Head>
        <title>E-Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
          rel="stylesheet"
        />
        <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script>
      </Head>

      <main className="">
        {/* <Navbar /> */}
        <Header />
        <NewCollections />
        <BestSeller />
        <OurProducts />
        <Reviews />
        <Policies />
        <Newsletter />
      </main>
    </>
  );
}
