import Head from "next/head";
import React, { useEffect } from "react";
import Header from "../components/header/Header";
import CardSlide from "../components/header/CardSlide";

export default function Home({ getUser }) {
  useEffect(() => {
    return () => {
      getUser();
    };
  }, []);

  return (
    <>
      <Head>
        <title>E-Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap"
          rel="stylesheet"
        />
        <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script>
      </Head>

      <main className="">
        <Header />
        <CardSlide/>
      </main>
    </>
  );
}
