import React, { useEffect, useState } from "react";
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../../src/theme/theme";
import FullLayout from "../../src/layouts/FullLayout";
import Orders from "../../src/components/dashboard/Orders";
import DBOrder from '../../models/Order'
import mongoose from "mongoose";

const Reporting = ({ orders }) => {
  return (
    <>
      <Head>
        <title>All Orders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline>
          <FullLayout>
            <Orders orders={orders} title={"All Orders"} />
          </FullLayout>
        </CssBaseline>
      </ThemeProvider>
    </>
  );
};
export async function getServerSideProps(context) {
  if (!mongoose.connection.readyState) {
    mongoose.connect(process.env.MONGO_URI);
  }
  const PromiseOrder = DBOrder.find({}).limit(10);

  const Order = await PromiseOrder;

  return {
    props: {
        orders: JSON.parse(JSON.stringify(Order)),
    },
  };
}
export default Reporting;
