import React from "react";
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../../src/theme/theme";
import FullLayout from "../../src/layouts/FullLayout";
import AllProductsTable from "../../src/components/dashboard/AllProductsTable";
import Product from '../../models/Product'
import mongoose from "mongoose";

const AllProducts = ({ tshirt, hoddies, mugs, stickers }) => {
    return (
        <>
            <Head>
                <title>All Products</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.ico" />
            </Head>
            <ThemeProvider theme={theme}>
                <CssBaseline >
                    <FullLayout>
                        <AllProductsTable products={tshirt} title={"T-Shirts"} />
                        <AllProductsTable products={hoddies} title={"Hoddies"} />
                        <AllProductsTable products={mugs} title={"Mugs"} />
                        <AllProductsTable products={stickers} title={"Stickers"} />
                    </FullLayout>
                </CssBaseline>
            </ThemeProvider>
        </>
    )
}

export async function getServerSideProps(context) {
    if (!mongoose.connection.readyState) {
        mongoose.connect(process.env.MONGO_URI)

    }
    const PromiseTshirt =  Product.find({ category: "T-shirt" },).sort({_id:-1}).limit(10);
    const PromiseHoddies =  Product.find({ category: "Hoodies" }).sort({_id:-1}).limit(10);
    const PromiseMugs =  Product.find({ category: "Mugs" }).sort({_id:-1}).limit(10);
    const PromiseStickers =  Product.find({ category: 'Sticker' }).sort({_id:-1}).limit(10);

    const tshirt = await PromiseTshirt
    const hoddies = await PromiseHoddies
    const mugs = await PromiseMugs
    const stickers = await PromiseStickers
    
    return {
        props: { 
            tshirt: JSON.parse(JSON.stringify(tshirt)),
            hoddies: JSON.parse(JSON.stringify(hoddies)),
            mugs: JSON.parse(JSON.stringify(mugs)),
            stickers: JSON.parse(JSON.stringify(stickers)),
         },
    }
}

export default AllProducts